apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-mq-spring-app-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mq/environments/staging/mq-spring-app
    repoURL: https://github.com/cloud-native-toolkit-demos/multi-tenancy-gitops-apps.git
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
