apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-scc
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  labels:
    gitops.tier.group: cntk
    gitops.tier.layer: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mq/environments/staging/scc
    repoURL: https://github.com/cloud-native-toolkit-demos/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
