apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-mq-infra-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mq/environments/mq-infra/overlays/staging
    repoURL: https://github.com/cloud-native-toolkit-demos/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
