resources:
 - ../../base
 - configmap/configmap.yaml
 - configmap/configmap-ccdt.yaml
 #- certificates/prod-mq-client-certificate.yaml
 #- certificates/prod-mq-server-certificate.yaml
 #- secrets/mq-client-jks-password-secret.yaml
patchesStrategicMerge:
 - mq-spring-app/deployment.yaml
