apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mq-infra-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mq/environments/prod/mq-infra
    repoURL: https://github.com/cloud-native-toolkit-demos/multi-tenancy-gitops-apps.git
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
  syncPolicy: {}
