resources:
 - ../../base
 - configmap/configmap.yaml
 - configmap/configmap-ccdt.yaml
 # - mq-spring-app/hooks/post-sync-job.yaml
 # - certificates/dev-mq-client-certificate.yaml
 # - certificates/dev-mq-server-certificate.yaml
 # - secrets/mq-client-jks-password-secret.yaml
patchesStrategicMerge:
 - mq-spring-app/deployment.yaml
