resources:
#- certificates/ci-mq-client-certificate.yaml
#- certificates/ci-mq-server-certificate.yaml
- configmaps/gitops-repo-configmap.yaml
#- eventlisteners/cntk-event-listener.yaml
#- triggerbindings/cntk-binding.yaml
#- triggertemplates/mq-infra-dev.yaml
#- triggertemplates/mq-spring-app-dev.yaml
- pipelines/ibm-test-pipeline-for-dev.yaml
- pipelines/ibm-test-pipeline-for-stage.yaml
#- pipelines/java-maven-dev-pipeline.yaml
- pipelines/mq-pipeline-dev.yaml
- pipelines/mq-spring-app-dev-pipeline.yaml
- roles/custom-pipeline-sa-clusterrole.yaml
- roles/custom-pipeline-sa-role.yaml
- roles/custom-ci-pipeline-sa-rolebinding.yaml
- roles/custom-dev-pipeline-sa-rolebinding.yaml
- roles/custom-staging-pipeline-sa-rolebinding.yaml
- roles/custom-prod-pipeline-sa-rolebinding.yaml
#- routes/cntk-route.yaml
#- secrets/artifactory-access-secret.yaml
- secrets/git-credentials-secret.yaml
- secrets/ibm-entitled-registry-credentials-secret.yaml
#- secrets/mq-client-jks-password-secret.yaml
- tasks/10-gitops.yaml
- tasks/10-gitops-for-mq.yaml
- tasks/10-gitops-promotion.yaml
- tasks/11-app-name.yaml
- tasks/12-functional-tests.yaml
- tasks/13-jmeter-performance-test.yaml
- tasks/13-cphtestp-performance-test.yaml
- tasks/4-smoke-tests-mq.yaml
- tasks/4-smoke-tests.yaml
- tasks/ibm-build-tag-push-v2-6-13.yaml
- tasks/ibm-helm-release-v2-6-13.yaml
- tasks/ibm-img-release-v2-6-13.yaml
- tasks/ibm-img-scan-v2-6-13.yaml
- tasks/ibm-java-maven-test-v2-6-13.yaml
- tasks/ibm-setup-v2-6-13.yaml
- tasks/ibm-tag-release-v2-6-13.yaml

# Automated promotion process triggers

# - triggertemplates/mq-infra-dev-triggertemplate.yaml
# - eventlisteners/mq-infra-dev-eventlistener.yaml
# - routes/mq-infra-dev-route.yaml
#
# - triggertemplates/mq-spring-app-dev-triggertemplate.yaml
# - eventlisteners/mq-spring-app-dev-eventlistener.yaml
# - routes/mq-spring-app-dev-route.yaml
#
# - triggertemplates/mq-infra-stage-triggertemplate.yaml
# - eventlisteners/mq-infra-stage-eventlistener.yaml
# - routes/mq-infra-stage-route.yaml
#
# - triggertemplates/mq-spring-app-stage-triggertemplate.yaml
# - eventlisteners/mq-spring-app-stage-eventlistener.yaml
# - routes/mq-spring-app-stage-route.yaml
