apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-mq-spring-app-instance
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mq/environments/mq-spring-app/overlays/dev
    repoURL: https://github.com/cloud-native-toolkit-demos/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
