resources:
 - ../../base
 - configmap/configmap.yaml
 - configmap/configmap-ccdt.yaml
 # - mq-spring-app/hooks/post-sync-job.yaml
 #- certificates/staging-mq-client-certificate.yaml
 #- certificates/staging-mq-server-certificate.yaml
 #- secrets/mq-client-jks-password-secret.yaml
patchesStrategicMerge:
 - mq-spring-app/deployment.yaml
