apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apic-pipelines-prod
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ci
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: apic/environments/single-cluster-cp4i
    repoURL: https://github.com/mq-apic-tutorial-ext/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
